Profiler Extension
teamneusta/pimcore-fixture-bundle pull request #19
Opened 2024-05-16 11:54 UTC by nehlsen

This PR drops a 🔥 extension for the Symfony Profiler. Now you can peep 👀 all the loaded fixtures, see how long each one took to load ⏱️, and check out the memory each one gobbled up 🧠. Straight fire! 🚀

2024-05-29 07:34 UTC, lukadschaak approved these changes

2024-05-29 07:35 UTC, lukadschaak requested changes
Pls fix phpstan

2024-06-11 18:52 UTC, nehlsen commented
@lukadschaak done! :boom:

2024-06-12 14:36 UTC, lukadschaak approved these changes

2024-06-12 19:50 UTC, jdreesen approved these changes
This looks great 😍 Thank you very much!

Just some nits.

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/DataCollector/FixtureLoaderCollector.php
> +class FixtureLoaderCollector extends AbstractDataCollector
What do you think about making everything `final` and `@internal`? This is no public API, right?

```suggestion
/**
 * @internal
 */
final class FixtureLoaderCollector extends AbstractDataCollector
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/EventListener/FixtureDependencyGraphSubscriber.php
> +class FixtureDependencyGraphSubscriber implements EventSubscriberInterface
```suggestion
/**
 * @internal
 */
final class FixtureDependencyGraphSubscriber implements EventSubscriberInterface
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/EventListener/TimingSubscriber.php
> +class TimingSubscriber implements EventSubscriberInterface
```suggestion
/**
 * @internal
 */
final class TimingSubscriber implements EventSubscriberInterface
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/FixtureReference/FixtureReference.php
> +class FixtureReference
```suggestion
/**
 * @internal
 */
final class FixtureReference
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/FixtureReference/FixtureReferenceResolver.php
> +class FixtureReferenceResolver
```suggestion
/**
 * @internal
 */
final class FixtureReferenceResolver
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/PerformanceInfo/PerformanceInfo.php
> +class PerformanceInfo
```suggestion
/**
 * @internal
 */
final class PerformanceInfo
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/Timing/Timing.php
> +class Timing
```suggestion
/**
 * @internal
 */
final class Timing
```

2024-06-12 19:50 UTC, jdreesen commented on src/Profiler/Timing/TimingCollector.php
> +class TimingCollector
```suggestion
/**
 * @internal
 */
final class TimingCollector
```

2024-06-12 19:50 UTC, jdreesen commented on config/services.yaml
> +    resource: '../src/Profiler/*'
I think this should only be loaded in `debug` mode, because the profiler is a development tool.

2024-07-02 07:52 UTC, jdreesen approved these changes

2024-07-02 08:05 UTC, merged